import assert from 'node:assert/strict';
import test,{after} from 'node:test';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {createServer} from 'vite';
const sql=new DatabaseSync(':memory:');for(const f of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sql.exec(readFileSync('drizzle/'+f,'utf8'));
let queue=Promise.resolve();globalThis.__bookingEnv={DB:{prepare(query){const stmt=sql.prepare(query);let args=[];const api={bind(...v){args=v;return api},async first(){return stmt.get(...args)??null},async all(){return {results:stmt.all(...args)}},async run(){const r=stmt.run(...args);return {meta:{changes:Number(r.changes)}}}};return api},batch(statements){const work=queue.then(async()=>{sql.exec('BEGIN');try{const out=[];for(const s of statements)out.push(await s.run());sql.exec('COMMIT');return out}catch(e){sql.exec('ROLLBACK');throw e}});queue=work.catch(()=>{});return work}}};
const vite=await createServer({configFile:false,appType:'custom',resolve:{alias:{'@':process.cwd()}},plugins:[{name:'booking-test',resolveId(id){if(id==='cloudflare:workers')return '\0booking-test'},load(id){if(id==='\0booking-test')return 'export const env=globalThis.__bookingEnv;'}}],server:{middlewareMode:true}});after(async()=>{await vite.close();sql.close();delete globalThis.__bookingEnv});const api=await vite.ssrLoadModule('/app/api/availability/route.ts');const requests=await vite.ssrLoadModule('/app/api/requests/route.ts');const {inBeirut,beirutDate,beirutTime}=await vite.ssrLoadModule('/lib/availability.ts');
const admin=crypto.randomUUID(),guest=crypto.randomUUID(),other=crypto.randomUUID();sql.prepare('INSERT INTO demo_auth(token,user_id,role,expires) VALUES(?,?,?,?)').run(admin,'admin','admin',Date.now()+1000000);
function req(body,who=admin,path='/api/availability'){return new Request('https://test.local'+path,{method:body?'POST':'GET',headers:{origin:'https://test.local',cookie:who===admin?`bexy_demo_auth=${admin}`:`bexy_session=${who}`,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})})}
const slot=crypto.randomUUID();const create={action:'create',id:slot,date:'2099-06-10',start:'10:00',end:'10:30'};
test('admin publishes slots, rejects overlaps and protects management',async()=>{assert.equal((await api.POST(req(create,guest))).status,403);assert.equal((await api.GET(req(null,guest,'/api/availability?admin=1'))).status,403);let r=await api.POST(req(create));assert.equal(r.status,200,await r.clone().text());assert.equal((await api.POST(req({...create,id:crypto.randomUUID(),start:'10:15',end:'10:45'}))).status,409);r=await api.GET(req(null,guest));const s=(await r.json()).slots[0];assert.equal(beirutTime(s.startsAt),'10:00');assert.equal(s.requestId,undefined);assert.equal(s.customer,undefined)});
test('concurrent customers cannot double-book; retry is idempotent',async()=>{const details={name:'Test Customer',email:'test@example.com',phone:'+96176123456',type:'Wedding',date:'2099-07-01',venue:'Beirut',message:'White flowers',consultationSlotId:slot};const ids=[crypto.randomUUID(),crypto.randomUUID()];const results=await Promise.all([requests.POST(req({id:ids[0],kind:'event',details},guest,'/api/requests')),requests.POST(req({id:ids[1],kind:'event',details},other,'/api/requests'))]);assert.equal(results.filter(r=>r.status===201).length,1);assert.equal(sql.prepare('SELECT COUNT(*) n FROM commerce_requests').get().n,1);const winner=results.findIndex(r=>r.status===201);assert.equal((await requests.POST(req({id:ids[winner],kind:'event',details},winner===0?guest:other,'/api/requests'))).status,201);const r=await api.GET(req(null,guest));assert.equal((await r.json()).slots.length,0);assert.equal((await api.POST(req({...create,action:'edit',version:0,start:'11:00',end:'11:30'}))).status,409)});
test('cancelling a booked consultation updates the customer request and permits a replacement slot',async()=>{const slotData=sql.prepare('SELECT * FROM consultation_slots WHERE id=?').get(slot);assert.equal((await api.POST(req({action:'cancel',id:slot,version:slotData.version}))).status,200);const order=sql.prepare('SELECT data FROM commerce_requests WHERE id=?').get(slotData.request_id);assert.equal(JSON.parse(order.data).details.consultationStatus,'Cancelled');assert.equal((await api.POST(req({...create,id:crypto.randomUUID()}))).status,200)});
test('Beirut time conversion works in summer and winter and rejects invalid dates',()=>{for(const day of ['2099-01-15','2099-07-15']){const utc=inBeirut(day,'10:45');assert.equal(beirutDate(utc),day);assert.equal(beirutTime(utc),'10:45')}assert.throws(()=>inBeirut('2099-02-30','10:00'))});
