import assert from 'node:assert/strict';
import test,{after} from 'node:test';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {createServer} from 'vite';
const sql=new DatabaseSync(':memory:');for(const f of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sql.exec(readFileSync('drizzle/'+f,'utf8'));
globalThis.__analyticsEnv={DB:{prepare(query){const stmt=sql.prepare(query);let args=[];const api={bind(...v){args=v;return api},async first(){return stmt.get(...args)??null},async all(){return {results:stmt.all(...args)}},async run(){const r=stmt.run(...args);return {meta:{changes:Number(r.changes)}}}};return api},async batch(statements){sql.exec('BEGIN');try{const out=[];for(const s of statements)out.push(await s.all());sql.exec('COMMIT');return out}catch(e){sql.exec('ROLLBACK');throw e}}}};
const vite=await createServer({configFile:false,appType:'custom',resolve:{alias:{'@':process.cwd()}},plugins:[{name:'analytics-test',resolveId(id){if(id==='cloudflare:workers')return '\0analytics-test'},load(id){if(id==='\0analytics-test')return 'export const env=globalThis.__analyticsEnv;'}}],server:{middlewareMode:true}});after(async()=>{await vite.close();sql.close();delete globalThis.__analyticsEnv});const api=await vite.ssrLoadModule('/app/api/analytics/route.ts');
const admin='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb';sql.prepare('INSERT INTO demo_auth(token,user_id,role,expires) VALUES(?,?,?,?)').run(admin,'admin','admin',Date.now()+1000000);let cookie='';const viewId=crypto.randomUUID();
function request(body,c=cookie,url='/api/analytics'){return new Request('https://test.local'+url,{method:body?'POST':'GET',headers:{origin:'https://test.local',cookie:c,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})})}
const event=(type,extra={})=>({id:crypto.randomUUID(),viewId,page:'/',type,...extra});
test('anonymous views, repeat-safe events, scroll and cart metrics persist without identity or location',async()=>{const view=event('page_view');let r=await api.POST(request(view));assert.equal(r.status,200);cookie=r.headers.get('set-cookie').split(';')[0];await api.POST(request(view));await api.POST(request(event('scroll',{depth:50,scrolling:true})));await api.POST(request(event('cart_add',{productId:'glitter',quantity:2})));r=await api.GET(request(null,`bexy_demo_auth=${admin}`));assert.equal(r.status,200);const d=await r.json();assert.equal(d.summary.visitors,1);assert.equal(d.summary.visits,1);assert.equal(d.summary.views,1);assert.equal(d.summary.cartAdds,1);assert.equal(d.summary.cartUnits,2);assert.equal(d.pages[0].averageDepth,50);assert.equal(d.active,1);const columns=sql.prepare('PRAGMA table_info(analytics_events)').all().map(r=>r.name);assert.ok(!columns.some(c=>/ip|email|location|name/.test(c)))});
test('heartbeats maintain presence and a return after inactivity starts a new visit',async()=>{await api.POST(request(event('heartbeat',{scrolling:true})));let r=await api.GET(request(null,`bexy_demo_auth=${admin}`));let d=await r.json();assert.equal(d.scrolling,1);assert.equal(d.summary.views,1);sql.prepare('UPDATE analytics_visitors SET last_seen=?').run(Date.now()-1800001);await api.POST(request(event('heartbeat')));r=await api.GET(request(null,`bexy_demo_auth=${admin}`));d=await r.json();assert.equal(d.summary.visits,2);assert.equal(d.summary.visitors,1);sql.prepare('UPDATE analytics_visitors SET last_seen=?').run(Date.now()-46000);r=await api.GET(request(null,`bexy_demo_auth=${admin}`));assert.equal((await r.json()).active,0)});
test('dashboard access is protected and admin traffic excluded',async()=>{assert.equal((await api.GET(request(null))).status,403);const before=sql.prepare('SELECT COUNT(*) n FROM analytics_events').get().n;const r=await api.POST(request(event('page_view'),`bexy_demo_auth=${admin}`));assert.equal((await r.json()).ignored,true);assert.equal(sql.prepare('SELECT COUNT(*) n FROM analytics_events').get().n,before)});
test('private routes, invalid events, unknown products and foreign origins are rejected',async()=>{assert.equal((await api.POST(request(event('page_view',{page:'/account?email=secret'})))).status,400);assert.equal((await api.POST(request(event('cart_add',{productId:'missing',quantity:1})))).status,400);assert.equal((await api.POST(new Request('https://test.local/api/analytics',{method:'POST',headers:{origin:'https://other.local'},body:'{}'}))).status,403)});
