'use client';
import Link from 'next/link';
import {Requests} from './requests';
import {useRouter} from 'next/navigation';
import {useState} from 'react';
import {ArrowRight,UserRound,LogOut,Heart,ShoppingBag,ShieldCheck} from 'lucide-react';
import {Input} from '@/components/ui/input';
import {useCms,type DemoUser} from './cms';
import {useShop} from './shop';
export function AuthPage({mode='login'}:{mode?:'login'|'signup'|'admin'}){const{setUser}=useCms();const router=useRouter();const[error,setError]=useState('');const[busy,setBusy]=useState(false);const signup=mode==='signup';async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');try{const body={action:mode,...Object.fromEntries(new FormData(e.currentTarget))};const r=await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json() as {user:DemoUser;error:string};if(!r.ok)throw Error(d.error);setUser(d.user);router.push(mode==='admin'?'/admin':'/account')}catch(e){setError(e instanceof Error?e.message:'Please try again.')}finally{setBusy(false)}}return <div className="auth-page"><div className="auth-brand"><img src="/images/logo.webp" alt="Bexy Flowers"/><p>YOUR MOMENTS, BEAUTIFULLY ARRANGED.</p></div><div className="auth-card"><span className="demo-pill">DEMO {mode==='admin'?'ADMIN':'ACCOUNT'}</span><h1>{mode==='admin'?'Welcome, Rebecca.':signup?'A little closer to lovely.':'Lovely to see you again.'}</h1><p>{mode==='admin'?'Manage your flowers, your website, and your business.':signup?'Create a mock account to explore the customer experience.':'Sign in to your demo Bexy account.'}</p><form onSubmit={submit} className="admin-form">{signup&&<label className="admin-field">Your name<Input name="name" required minLength={2} maxLength={100} autoComplete="name"/></label>}<label className="admin-field">{mode==='admin'?'Username':'Email'}<Input name={mode==='admin'?'username':'email'} type={mode==='admin'?'text':'email'} required autoComplete="username" placeholder={mode==='admin'?'admin':'you@example.com'}/></label>{signup&&<label className="admin-field">Phone number<Input name="phone" type="tel" autoComplete="tel" placeholder="Optional demo number" maxLength={30}/></label>}<label className="admin-field">Password<Input name="password" type="password" required minLength={signup?6:1} maxLength={128} autoComplete={signup?'new-password':'current-password'}/></label>{error&&<p role="alert" className="form-error">{error}</p>}<button className="primary full" disabled={busy}>{busy?'Please wait…':signup?'Create account':'Sign in'}<ArrowRight size={16}/></button></form>{mode==='admin'?<p className="auth-footnote">Demo access: <code>admin</code> / <code>admin123</code></p>:<p className="auth-footnote">{signup?'Already have an account?':'New to Bexy?'} <Link href={signup?'/login':'/signup'}>{signup?'Sign in':'Create an account'}</Link></p>}<p className="fine-print">This is a mock experience. No verification emails are sent.</p></div></div>}
export function AccountPage(){const{user,authLoaded,logout}=useCms();const{data,bag}=useShop();if(!authLoaded)return <div className="loading-surface">Loading your account…</div>;if(!user)return <AuthPage/>;return <div className="account-page"><span className="demo-pill">DEMO ACCOUNT</span><h1>Hello, <em>{user.name.split(' ')[0]}.</em></h1><p>Your favorite flowers, all in one place.</p><div className="account-grid"><article><UserRound/><h2>Your details</h2><p>{user.name}<br/>{user.email}<br/>{user.phone}</p></article><Link href="/collection?favorites=true"><Heart/><h2>Your favorites</h2><p>{data.favorites.length} saved arrangements</p></Link><button onClick={()=>bag(true)}><ShoppingBag/><h2>Your bag</h2><p>{data.cart.reduce((s,i)=>s+i.quantity,0)} items waiting for you</p></button>{user.role==='admin'&&<Link href="/admin"><ShieldCheck/><h2>Admin studio</h2><p>Website, orders, and analytics</p></Link>}</div><div className="account-orders"><Requests/></div><button className="outline" onClick={logout}><LogOut size={16}/>Sign out</button></div>}
