'use client';
import Link from 'next/link';
import {PageHero} from './page-hero';
import {useRef} from 'react';
import {CustomerStories} from './store-content';
import {GiftComparison} from './gift-comparison';
import {ArrowRight,ChevronLeft,ChevronRight,MoveHorizontal} from 'lucide-react';
import {EditableText,EditableImage,EditableSection,useCms} from './cms';
import {ProductCard} from './shop';
import {occasionEdits,type Product} from '@/lib/catalog';
import {sortProductsForHome} from '@/lib/rebecca-catalog';
function ProductRail({products,id,title,href}:{products:Product[];id:string;title:string;href:string}){const ref=useRef<HTMLDivElement>(null);const{editing,openProduct}=useCms();return <EditableSection className="reference-products" editKey={id}><div className="reference-section-heading"><EditableText as="h2" editKey={id+'-title'}>{title}</EditableText><Link href={href}>View all <ChevronRight size={14}/></Link></div>{editing&&<button className="cms-add-product" onClick={()=>openProduct(null)}>+ Add a product</button>}<div ref={ref} className="reference-product-rail">{products.map(p=><ProductCard key={p.id} product={p}/>)}</div><div className="rail-controls"><button aria-label={'Previous '+title.toLowerCase()} onClick={()=>ref.current?.scrollBy({left:-ref.current.clientWidth,behavior:'smooth'})}><ChevronLeft size={18}/></button><span>EXPLORE THE EDIT</span><button aria-label={'Next '+title.toLowerCase()} onClick={()=>ref.current?.scrollBy({left:ref.current.clientWidth,behavior:'smooth'})}><ChevronRight size={18}/></button></div></EditableSection>}
export function HomePage(){const{cms,editing}=useCms();const visible=cms.products.filter(p=>p.active!==false||editing);const flowers=sortProductsForHome(visible.filter(p=>p.kind!=='accessory'));const accessories=visible.filter(p=>p.kind==='accessory');return <>
<PageHero id="pages-section-1" eyebrow="THE BEXY FLOWERS COLLECTION" eyebrowKey="reference-hero-overline" title={<>Flowers, with<br/>feeling.</>} titleKey="reference-hero-title" description="For your kind of love. Thoughtfully arranged by Rebecca, made personal by you." image="/images/homepage-hero.png" imageKey="reference-hero-image" alt="Bexy Flowers signature bouquet hero" caption="THE SIGNATURE COLLECTION · 2026" actions={[{label:'Explore flowers',href:'/collection'},{label:'Make it yours',href:'/customize'}]} contentId="latest-arrangements"/><div id="latest-arrangements" className="bexy-section-anchor"/>
<ProductRail products={flowers} id="pages-section-5" title="The latest arrangements" href="/collection"/>
<PageHero feature id="pages-section-8" eyebrow="WEDDINGS & EVENTS" title="Your forever flowers." titleKey="reference-campaign-title" description="From your first bouquet to the final celebration. Flowers that belong to your story." image="/images/wedding-wide.webp" imageKey="reference-campaign-image" alt="White wedding flowers in an elegant interior" caption="YOUR DAY. BEAUTIFULLY BEXY." actions={[{label:'Weddings & Events',href:'/wedding-and-events'}]} contentId="home-finishing-touches"/><div id="home-finishing-touches" className="bexy-section-anchor"/>
<ProductRail products={accessories} id="home-accessories" title="The finishing touches" href="/accessories"/>
<PageHero feature id="home-signature-look" eyebrow="THE DETAILS MAKE IT YOURS" title="The signature touch." titleKey="home-signature-title" description="Seasonal flowers. Sculptural wrapping. A ribbon tied by hand. Discover the details that make a bouquet unmistakably Bexy." image="/images/signature-atelier-v2.webp" imageKey="home-signature-photo-v2" alt="A florist finishing a mixed ivory and blush bouquet with a gold ribbon" caption="THE BEXY SIGNATURE" actions={[{label:'Explore arrangements',href:'/collection'},{label:'Make it yours',href:'/customize'}]} contentId="discover-your-color"/><div id="discover-your-color" className="bexy-section-anchor"/>
<GiftComparison/>
<EditableSection className="reference-occasions occasion-editorial" editKey="pages-section-12"><div className="occasion-editorial-heading"><EditableText as="p" className="eyebrow" editKey="occasion-editorial-eyebrow">EVERY MOMENT HAS ITS FLOWERS</EditableText><EditableText as="h2" editKey="reference-occasion-heading">For every occasion</EditableText><EditableText as="p" editKey="occasion-editorial-intro">The big days. The little gestures. The moments in between.</EditableText></div><div className="reference-occasion-grid">{occasionEdits.map(o=><Link key={o.name} href={'/collection?occasion='+encodeURIComponent(o.name)}><EditableImage editKey={'occasion-edit-image-'+o.id} src={'/images/'+o.image+'.webp'} alt={o.name+' flower collection'} width="700" height="850" loading="lazy"/><span><EditableText as="span" editKey={'occasion-edit-label-'+o.id}>{o.name}</EditableText><small>Explore the edit</small><ArrowRight size={18}/></span></Link>)}</div></EditableSection>
<CustomerStories/>
</>}
