'use client';
import Link from 'next/link';
import {usePathname} from 'next/navigation';
import {ArrowUpRight,UserRound} from 'lucide-react';
import {useState} from 'react';
import {NavigationMenu,NavigationMenuList,NavigationMenuItem,NavigationMenuTrigger,NavigationMenuContent,NavigationMenuLink} from '@/components/ui/navigation-menu';
import {Accordion,AccordionItem,AccordionTrigger,AccordionContent} from '@/components/ui/accordion';
import {occasions} from '@/lib/catalog';
import {useCms} from './cms';
export function CollectionLinks({close=()=>{}}:{close?:()=>void}){const{cms}=useCms();const years=[...new Set([2026,2025,...cms.products.flatMap(p=>p.years??[])])].sort((a,b)=>b-a);return <><div><h3>Collections</h3><Link href="/collection" onClick={close}>View all flowers</Link><Link href="/collection?category=Signature%20bouquets" onClick={close}>Signature bouquets</Link><Link href="/collection?sort=newest" onClick={close}>New arrivals</Link><Link href="/collection?favorites=true" onClick={close}>Your favorites</Link></div><div><h3>By occasion</h3>{occasions.map(o=><Link key={o} href={'/collection?occasion='+encodeURIComponent(o)} onClick={close}>{o}</Link>)}</div><div><h3>By year</h3>{years.map(y=><Link key={y} href={'/collection?year='+y} onClick={close}>Collection {y}</Link>)}<Link href="/wedding-and-events" onClick={close}>Weddings & Events</Link></div></>}
export function DesktopNavigation(){const[value,setValue]=useState('');const{cms}=useCms();const accessories=cms.products.filter(p=>p.kind==='accessory'&&p.active!==false);const cats=[...new Set(accessories.map(p=>p.category))];return <NavigationMenu className="reference-navigation" viewport={false} value={value} onValueChange={setValue} aria-label="Main navigation"><NavigationMenuList><NavigationMenuItem><NavigationMenuTrigger>Collections</NavigationMenuTrigger><NavigationMenuContent className="collection-mega"><div className="mega-columns"><CollectionLinks close={()=>setValue('')}/><Link href="/collection?occasion=Valentine%E2%80%99s%20Day" className="mega-feature" onClick={()=>setValue('')}><img src="/images/valentine.webp" alt="Red rose Valentine bouquet"/><span>The romance edit</span></Link></div></NavigationMenuContent></NavigationMenuItem><NavigationMenuItem><NavigationMenuTrigger>Accessories</NavigationMenuTrigger><NavigationMenuContent className="accessory-mega"><div className="mega-columns"><div><h3>The finishing touches</h3><Link href="/accessories" onClick={()=>setValue('')}>View all accessories</Link>{cats.map(c=><Link key={c} href={'/accessories?category='+encodeURIComponent(c)} onClick={()=>setValue('')}>{c}</Link>)}</div>{accessories.slice(0,2).map(p=><Link className="mega-feature" href={'/accessories?category='+encodeURIComponent(p.category)} key={p.id} onClick={()=>setValue('')}><img src={p.image} alt={p.name}/><span>{p.name}</span></Link>)}</div></NavigationMenuContent></NavigationMenuItem><NavigationMenuItem><NavigationMenuLink asChild><Link href="/customize">Customize</Link></NavigationMenuLink></NavigationMenuItem><NavigationMenuItem><NavigationMenuLink asChild><Link href="/wedding-and-events">Weddings & Events</Link></NavigationMenuLink></NavigationMenuItem></NavigationMenuList></NavigationMenu>}
export function MobileNavigation({close}:{close:()=>void}){const{cms,user}=useCms();const path=usePathname();const active=(href:string)=>path===href?'page' as const:undefined;return <div className="bexy-menu-body"><nav className="bexy-menu-links" aria-label="Mobile navigation"><p className="bexy-menu-eyebrow">EXPLORE</p><Link className="bexy-menu-main" aria-current={active('/')} href="/" onClick={close}><span className="bexy-menu-label">Home</span></Link><Accordion type="single" collapsible><AccordionItem value="collections"><AccordionTrigger className={path==='/collection'?'current-section':''}><span className="bexy-menu-label">Collections</span></AccordionTrigger><AccordionContent><div className="bexy-menu-subgroups"><CollectionLinks close={close}/></div></AccordionContent></AccordionItem><AccordionItem value="accessories"><AccordionTrigger className={path==='/accessories'?'current-section':''}><span className="bexy-menu-label">Accessories</span></AccordionTrigger><AccordionContent><div className="bexy-menu-subgroups"><div><Link href="/accessories" onClick={close}>View all accessories</Link>{[...new Set(cms.products.filter(p=>p.kind==='accessory'&&p.active!==false).map(p=>p.category))].map(c=><Link href={'/accessories?category='+encodeURIComponent(c)} onClick={close} key={c}>{c}</Link>)}</div></div></AccordionContent></AccordionItem></Accordion><Link className="bexy-menu-main" href="/customize" aria-current={active('/customize')} onClick={close}><span className="bexy-menu-label">Customize<small>Your bouquet, your way</small></span><ArrowUpRight size={21}/></Link><Link className="bexy-menu-main" href="/wedding-and-events" aria-current={active('/wedding-and-events')} onClick={close}><span className="bexy-menu-label">Weddings & Events</span></Link></nav><div className="bexy-menu-bottom"><Link href="/about" aria-current={active('/about')} onClick={close}>Our story <ArrowUpRight size={17}/></Link><Link href={user?'/account':'/login'} onClick={close}><UserRound size={18}/>{user?'Your account':'Sign in / Sign up'}</Link></div></div>}
