'use client';
import Link from 'next/link';
import {ArrowDown,ArrowUpRight} from 'lucide-react';
import {useEffect,useRef,type ReactNode} from 'react';
import {EditableSection,EditableText,EditableImage} from './cms';
type HeroProps={id:string;eyebrow:string;title:ReactNode;description:string;image?:string;alt?:string;imageKey?:string;titleKey?:string;eyebrowKey?:string;descriptionKey?:string;caption?:string;captionKey?:string;actions?:{label:string;href?:string;onClick?:()=>void}[];feature?:boolean;contentId?:string;compact?:boolean;contain?:boolean;dynamicTitle?:boolean};
export function PageHero({id,eyebrow,title,description,image='/images/editorial-signature.webp',alt='',imageKey,titleKey,eyebrowKey,descriptionKey,caption='DESIGNED BY REBECCA · LEBANON',captionKey,actions=[],contentId,dynamicTitle=false,feature=false}:HeroProps){
const frame=useRef<HTMLDivElement>(null);
useEffect(()=>{const el=frame.current;if(!el)return;const motion=window.matchMedia('(prefers-reduced-motion: reduce)');let raf=0;let visible=true;const paint=()=>{raf=0;if(!visible||motion.matches){el.style.setProperty('--hero-drift','0px');return}const rect=el.getBoundingClientRect();const offset=Math.min(el.clientHeight,Math.max(-el.clientHeight,-rect.top))*.16;el.style.setProperty('--hero-drift',offset+'px')};const schedule=()=>{if(!raf)raf=requestAnimationFrame(paint)};const observer=new IntersectionObserver(entries=>{visible=entries[0].isIntersecting;if(visible)schedule()});observer.observe(el);window.addEventListener('scroll',schedule,{passive:true});window.addEventListener('resize',schedule);motion.addEventListener('change',schedule);schedule();return()=>{cancelAnimationFrame(raf);observer.disconnect();window.removeEventListener('scroll',schedule);window.removeEventListener('resize',schedule);motion.removeEventListener('change',schedule)}},[]);
return <EditableSection editKey={id} className={'bexy-page-hero bexy-immersive-hero'+(feature?' bexy-feature-hero':'')}><div ref={frame} className="bexy-hero-layout"><figure className="bexy-hero-art"><EditableImage editKey={imageKey??id+'-image'} src={image} alt={alt} width="1600" height="1100" fetchPriority={feature?'auto':'high'} loading={feature?'lazy':'eager'} style={{objectPosition:imageKey==='reference-hero-image'?'64% center':id==='pages-section-26'?'50% 35%':'center'}}/></figure><div className="bexy-hero-shade" aria-hidden="true"/><div className="bexy-hero-copy"><EditableText as="p" className="bexy-hero-eyebrow" editKey={eyebrowKey??id+'-eyebrow'}>{eyebrow}</EditableText>{dynamicTitle?<h1>{title}</h1>:<EditableText as={feature?'h2':'h1'} editKey={titleKey??id+'-title'}>{title}</EditableText>}<EditableText as="p" className="bexy-hero-description" editKey={descriptionKey??id+'-description'}>{description}</EditableText>{actions.length>0&&<div className="bexy-hero-actions">{actions.map((a,i)=>a.onClick?<button key={a.label} onClick={a.onClick} className={i===0?'primary':'bexy-quiet-link'}>{a.label}<ArrowUpRight size={17}/></button>:<Link key={a.label} href={a.href??'/collection'} className={i===0?'primary':'bexy-quiet-link'}>{a.label}{i===0?<ArrowUpRight size={17}/>:<ArrowDown size={16}/>}</Link>)}</div>}</div><div className="bexy-hero-foot"><EditableText as="span" editKey={captionKey??id+'-caption'}>{caption}</EditableText>{contentId&&<a href={'#'+contentId} className="bexy-scroll-cue">Scroll to explore <ArrowDown size={17}/></a>}<span>MADE PERSONAL, IN LEBANON</span></div></div></EditableSection>}
export function DiscoverBexy(){return <EditableSection editKey="shared-discover-bexy" className="bexy-discover"><div><EditableText as="p" className="eyebrow" editKey="shared-discover-eyebrow">MORE FROM BEXY</EditableText><EditableText as="h2" editKey="shared-discover-title">Find your next beautiful thing.</EditableText></div><div className="bexy-discover-links">{[{name:'The flower collection',href:'/collection',copy:'From everyday gestures to grand declarations.'},{name:'Made by you',href:'/customize',copy:'Your flowers, your palette, your finishing touch.'},{name:'Weddings & events',href:'/wedding-and-events',copy:'For the moments that become memories.'}].map((a,i)=><Link href={a.href} key={a.href}><span>0{i+1}</span><div><EditableText as="h3" editKey={'shared-discover-card-title-'+i}>{a.name}</EditableText><EditableText as="p" editKey={'shared-discover-card-copy-'+i}>{a.copy}</EditableText></div><ArrowUpRight size={23}/></Link>)}</div></EditableSection>}
