'use client';
import {useEffect,useState} from 'react';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from '@/components/ui/table';
import {money} from '@/lib/demo-data';
import {orderStatuses,eventStatuses,type StoreRequest} from '@/lib/commerce';
export function Requests({admin=false,onUpdate}:{admin?:boolean;onUpdate?:()=>void}){const[rows,setRows]=useState<StoreRequest[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[selected,setSelected]=useState<StoreRequest|null>(null),[busy,setBusy]=useState(false),[search,setSearch]=useState(''),[kind,setKind]=useState('all');
async function load(){setLoading(true);setError('');try{const r=await fetch('/api/requests'+(admin?'?admin=1':''));const j=await r.json() as {error?:string;requests:StoreRequest[]};if(!r.ok)throw Error(j.error);setRows(j.requests)}catch(e){setError(e instanceof Error?e.message:'Unable to load requests')}finally{setLoading(false)}}useEffect(()=>{void load()},[admin]);
async function update(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!selected||busy)return;setBusy(true);setError('');const f=new FormData(e.currentTarget);try{const r=await fetch('/api/requests',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'update',id:selected.id,version:selected.version,status:f.get('status'),notes:f.get('notes'),shipping:Math.round(Number(f.get('shipping')??0)*100),paid:Math.round(Number(f.get('paid')??0)*100),refund:Math.round(Number(f.get('refund')??0)*100),payment:f.get('payment')??'Not recorded'})});const j=await r.json() as {error?:string;requests:StoreRequest[]};if(!r.ok)throw Error(j.error);setSelected(null);await load();onUpdate?.()}catch(e){setError(e instanceof Error?e.message:'Unable to save')}finally{setBusy(false)}}
const visible=rows.filter(r=>(kind==='all'||r.kind===kind)&&[r.id,...Object.values(r.data.details)].join(' ').toLowerCase().includes(search.toLowerCase()));return <article className="admin-card requests-panel"><div className="card-heading"><div><h2>{admin?'Orders & wedding enquiries':'Your requests'}</h2><p>{admin?'Submitted through your website. Requests need confirmation; stock is checked at submission but is not reserved.':'Track requests from this browser and your signed-in account.'}</p></div><button className="outline compact" onClick={load} disabled={loading}>Refresh</button></div>{admin&&<div className="table-toolbar"><Input aria-label="Search requests" placeholder="Name, phone, email or reference" value={search} onChange={e=>setSearch(e.target.value)}/><Select value={kind} onValueChange={setKind}><SelectTrigger aria-label="Request type"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All requests</SelectItem><SelectItem value="order">Flower orders</SelectItem><SelectItem value="event">Weddings & events</SelectItem></SelectContent></Select></div>}{error&&!selected&&<p role="alert" className="form-error">{error}</p>}{loading?<p className="card-empty">Loading requests…</p>:!visible.length?<p className="card-empty">No requests yet.</p>:<Table><TableHeader><TableRow>{['Reference','Customer / date','Type','Status','Paid',''].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{visible.map(r=><TableRow key={r.id}><TableCell>{r.id.slice(0,8).toUpperCase()}</TableCell><TableCell>{String(r.data.details.name)}<small>{new Date(r.createdAt).toLocaleDateString('en-GB',{timeZone:'Asia/Beirut'})}</small></TableCell><TableCell>{r.kind==='order'?'Flowers':'Wedding / event'}</TableCell><TableCell>{r.data.status}</TableCell><TableCell>{r.kind==='order'?money(r.data.paid-r.data.refund):'—'}</TableCell><TableCell><button className="table-action" onClick={()=>{setError('');setSelected(r)}}>{admin?'Manage':'View'}</button></TableCell></TableRow>)}</TableBody></Table>}
<Dialog open={!!selected} onOpenChange={v=>{if(!v){setSelected(null);setError('')}}}><DialogContent className="request-dialog"><DialogTitle>{selected?.kind==='order'?'Flower order':'Wedding & event enquiry'} · {selected?.id.slice(0,8).toUpperCase()}</DialogTitle><DialogDescription>{admin?'Update the request and record payments already received. Saving does not charge, refund, or message the customer.':'Rebecca will confirm availability, pricing and arrangements with you.'}</DialogDescription>{selected&&<><dl className="request-details">{Object.entries(selected.data.details).filter(([k])=>k!=='consent').map(([k,v])=>v&&<div key={k}><dt>{k.replace(/([A-Z])/g,' $1')}</dt><dd>{String(v)}</dd></div>)}</dl>{selected.data.lines.map((l,i)=><div className="request-line" key={i}><strong>{l.quantity} × {l.name} · {l.size}</strong><span>{money(l.unitPrice*l.quantity)}</span>{l.design&&<p style={{whiteSpace:'pre-line'}}>{l.design}</p>}{l.note&&<p>{l.note}</p>}</div>)}{selected.kind==='order'&&<p>Flowers {money(selected.data.subtotal)} · Delivery {money(selected.data.shipping)} · Paid {money(selected.data.paid)} · Refunded {money(selected.data.refund)}<br/><small>Delivery is provisional until confirmed. Custom bouquet costs need separate expense tracking.</small></p>}{admin?<form className="admin-form" onSubmit={update}><label className="admin-field">Status<Select name="status" defaultValue={selected.data.status}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{(selected.kind==='order'?orderStatuses:eventStatuses).map(s=><SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent></Select></label>{selected.kind==='order'&&<><div className="form-grid">{[{name:'shipping',label:'Confirmed delivery fee ($)'},{name:'paid',label:'Total received to date ($)'},{name:'refund',label:'Total refunded to date ($)'}].map(f=><label className="admin-field" key={f.name}>{f.label}<Input name={f.name} type="number" step="0.01" min="0" max="1000000" required defaultValue={Number(selected.data[f.name as 'shipping'|'paid'|'refund'])/100}/></label>)}</div><label className="admin-field">Payment method<Select name="payment" defaultValue={selected.data.payment}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{['Not recorded','Cash on delivery','Bank transfer','Other offline payment'].map(s=><SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent></Select></label></>}<label className="admin-field">Private studio notes<Textarea name="notes" maxLength={3000} defaultValue={selected.data.notes}/></label>{error&&<p role="alert" className="form-error">{error}</p>}<button className="primary" disabled={busy}>{busy?'Saving…':'Save request'}</button><details><summary>Update history</summary>{selected.data.history.slice().reverse().map((h,i)=><p key={i}>{new Date(h.date).toLocaleString('en-GB',{timeZone:'Asia/Beirut'})} · {h.note}</p>)}</details></form>:<p>Status: <strong>{selected.data.status}</strong></p>}</>}</DialogContent></Dialog></article>}
