'use client';
import Link from 'next/link';
import {Truck,Flower2,ArrowRight} from 'lucide-react';
import {EditableText,EditableImage,EditableSection,useCms,uploadImage} from './cms';
import {useState} from 'react';
import {toast} from 'sonner';
import {Accordion,AccordionItem,AccordionTrigger,AccordionContent} from '@/components/ui/accordion';
import {Carousel,CarouselContent,CarouselItem,CarouselNext,CarouselPrevious} from '@/components/ui/carousel';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Switch} from '@/components/ui/switch';
export const storeDetails=[
 {key:'delivery-areas',title:'Areas we serve',text:'Delivery is available by arrangement in Lebanon. Check your area with Rebecca before confirming an order.'},
 {key:'delivery-fees',title:'Delivery charges',text:'Delivery is quoted for your address. The delivery fee is separate from the bouquet price.'},
 {key:'delivery-timing',title:'Preparation & available dates',text:'Share your preferred date with Rebecca. Timing depends on the flowers, design and delivery area; a selected date is a request until confirmed.'},
 {key:'flower-substitutions',title:'Seasonal flowers',text:'Flowers can vary with the season. Ask Rebecca to confirm the flowers and any proposed substitutions before your order is finalized.'},
 {key:'flower-care',title:'Keep your flowers beautiful',text:'For cut flowers in a vase, use clean water, remove leaves below the waterline and refresh the water regularly. Keep flowers away from direct sunlight, heat and ripening fruit. Ask Rebecca for care instructions suited to boxed or specially finished arrangements.'},
 {key:'wedding-booking',title:'Booking your celebration',text:'Your date is confirmed only after Rebecca agrees to the proposal and booking terms. Ask about availability, any deposit, installation, delivery and changes before confirming.'}
];
function ContentPhotoUpload({editKey,label}:{editKey:string;label:string}){const{cms,edit}=useCms();const[uploading,setUploading]=useState(false);return <div className="content-photo-upload"><label className="admin-field">{label}<Input type="file" accept="image/png,image/jpeg,image/webp" disabled={uploading} onChange={async e=>{const file=e.target.files?.[0];if(!file)return;setUploading(true);try{edit(editKey,{src:await uploadImage(file)});toast.success('Photo ready. Save content to keep it.')}catch(e){toast.error(e instanceof Error?e.message:'Upload failed')}finally{setUploading(false)}}}/></label>{uploading&&<p>Uploading…</p>}{cms.entries[editKey]?.src&&<><img src={cms.entries[editKey]?.src} alt={label} width="140" height="140"/><button type="button" className="text-link" onClick={()=>edit(editKey,{src:undefined})}>Remove photo</button></>}</div>}
export function DeliveryPanel(){return <div className="delivery-panel"><h3><Truck size={18}/>Delivery in Lebanon</h3><Accordion type="single" collapsible>{storeDetails.slice(0,3).map(d=><AccordionItem key={d.key} value={d.key}><AccordionTrigger>{d.title}</AccordionTrigger><AccordionContent><EditableText editKey={d.key}>{d.text}</EditableText></AccordionContent></AccordionItem>)}</Accordion></div>}
export function FlowerCare(){return <div className="flower-care"><h3><Flower2 size={18}/>A little care goes a long way</h3><Accordion type="single" collapsible>{storeDetails.slice(3,5).map(d=><AccordionItem key={d.key} value={d.key}><AccordionTrigger>{d.title}</AccordionTrigger><AccordionContent><EditableText editKey={d.key}>{d.text}</EditableText></AccordionContent></AccordionItem>)}</Accordion></div>}
export function RebeccaStory(){return <EditableSection className="rebecca-story" editKey="rebecca-personal-story"><figure><EditableImage editKey="rebecca-personal-photo" src="/images/about.jpg" alt="Rebecca with flower arrangements, from the Bexy Flowers About page" width="800" height="1000" loading="lazy"/></figure><div><EditableText as="p" className="eyebrow" editKey="rebecca-personal-eyebrow">THE PERSON BEHIND YOUR FLOWERS</EditableText><EditableText as="h2" editKey="rebecca-personal-title">Meet Rebecca.</EditableText><EditableText editKey="rebecca-personal-copy">Rebecca Yameen is the owner of Bexy Flowers in Lebanon. She designs flowers for personal gifts, weddings and events, with colors and finishing touches chosen around each occasion.</EditableText><EditableText editKey="rebecca-personal-invitation">Have a favorite flower or a particular feeling in mind? Start with that. Rebecca can help you turn it into an arrangement.</EditableText><Link className="text-link" href="/customize">Create something personal <ArrowRight size={16}/></Link></div></EditableSection>}
export function StudioMoments(){const{cms,editing}=useCms();const photos=[1,2,3].filter(i=>cms.entries[`studio-moment-${i}`]?.src||editing);if(!photos.length)return null;return <EditableSection className="studio-moments section" editKey="studio-moments"><EditableText as="h2" editKey="studio-moments-title">Inside Rebecca’s studio</EditableText>{editing&&<p className="fine-print">Upload genuine behind-the-scenes photographs. Unfilled slots stay hidden from customers.</p>}<div>{photos.map(i=><figure key={i}>{cms.entries[`studio-moment-${i}`]?.src?<EditableImage editKey={`studio-moment-${i}`} alt="Behind the scenes at Bexy Flowers" width="700" height="850"/>:<p>Upload studio photo {i} in Admin → Shop settings.</p>}<EditableText as="figcaption" editKey={`studio-moment-caption-${i}`}>{editing?'Add a caption':''}</EditableText></figure>)}</div></EditableSection>}
export function CustomerStories(){const{cms,editing}=useCms();const ids=[1,2,3,4].filter(i=>{const q=cms.entries[`review-${i}-quote`];return q?.hidden===false&&q.text?.trim()&&cms.entries[`review-${i}-name`]?.text?.trim()});if(!ids.length)return editing?<div className="review-empty section">Customer stories are ready for genuine reviews. Add approved reviews and photos in Admin → Shop settings.</div>:null;return <EditableSection className="customer-stories section" editKey="customer-stories"><EditableText className="eyebrow" as="p" editKey="customer-stories-eyebrow">YOUR BEXY MOMENTS</EditableText><EditableText as="h2" editKey="customer-stories-title">Flowers worth remembering.</EditableText><Carousel opts={{align:'start'}} aria-label="Customer stories"><div className="wedding-slider-controls"><span>Shared by our customers</span><CarouselPrevious/><CarouselNext/></div><CarouselContent>{ids.map(i=><CarouselItem key={i}><article>{cms.entries[`review-${i}-photo`]?.src&&<EditableImage editKey={`review-${i}-photo`} alt="Customer-shared Bexy Flowers photograph" width="500" height="500"/>}<blockquote><EditableText editKey={`review-${i}-quote`}/></blockquote><EditableText as="p" editKey={`review-${i}-name`}/></article></CarouselItem>)}</CarouselContent></Carousel></EditableSection>}
export function WeddingJourney(){return <EditableSection className="wedding-journey section" editKey="wedding-journey"><EditableText as="p" className="eyebrow" editKey="wedding-journey-eyebrow">FROM YOUR FIRST IDEA TO YOUR DAY</EditableText><EditableText as="h2" editKey="wedding-journey-title">Let’s plan it together.</EditableText><ol>{[['Consultation','Share your date, venue, colors and budget with Rebecca.'],['Your proposal','Review the flowers, styling, scope and quote together.'],['Confirmation','Agree on the final details and booking terms.'],['Installation','Coordinate access, setup and delivery for your celebration.']].map(([title,copy],i)=><li key={title}><span>0{i+1}</span><EditableText as="h3" editKey={`wedding-step-${i}-title`}>{title}</EditableText><EditableText editKey={`wedding-step-${i}-copy`}>{copy}</EditableText></li>)}</ol><EditableText className="booking-note" editKey="wedding-booking">{storeDetails[5].text}</EditableText><a className="primary" href="#event-inquiry">Plan a consultation <ArrowRight size={16}/></a></EditableSection>}
export function StoreContentSettings(){const{cms,edit,save,busy,dirty}=useCms();return <div className="store-content-settings"><h2>Delivery, care & booking information</h2><p>Replace these provisional details with Rebecca’s confirmed policies. They update the product pages and wedding page.</p>{storeDetails.map(d=><label className="admin-field" key={d.key}>{d.title}<Textarea value={cms.entries[d.key]?.text??d.text} onChange={e=>edit(d.key,{text:e.target.value})} maxLength={5000}/></label>)}<h2>Behind the scenes</h2><p>Add genuine photographs from Rebecca’s studio. They appear on the About page after saving.</p>{[1,2,3].map(i=><div key={i}><ContentPhotoUpload editKey={`studio-moment-${i}`} label={`Studio photo ${i}`}/><label className="admin-field">Caption<Input value={cms.entries[`studio-moment-caption-${i}`]?.text??''} onChange={e=>edit(`studio-moment-caption-${i}`,{text:e.target.value})}/></label></div>)}<h2>Genuine customer stories</h2><p>Add only real customer feedback and photographs you have permission to publish. Empty or unpublished reviews remain hidden.</p>{[1,2,3,4].map(i=>{const key=`review-${i}-quote`;const valid=!!cms.entries[key]?.text?.trim()&&!!cms.entries[`review-${i}-name`]?.text?.trim();return <div className="review-editor" key={i}><h3>Story {i}</h3><label className="admin-field">Customer display name<Input value={cms.entries[`review-${i}-name`]?.text??''} onChange={e=>edit(`review-${i}-name`,{text:e.target.value})}/></label><label className="admin-field">Customer’s own words<Textarea value={cms.entries[key]?.text??''} onChange={e=>edit(key,{text:e.target.value,hidden:cms.entries[key]?.hidden??true})}/></label><ContentPhotoUpload editKey={`review-${i}-photo`} label="Customer photo (optional)"/><label className="switch-row">Approved for publication<Switch checked={valid&&cms.entries[key]?.hidden===false} disabled={!valid} onCheckedChange={v=>edit(key,{hidden:!v})}/></label></div>})}<button className="primary" disabled={!dirty||busy} onClick={()=>void save()}>Save content</button></div>}
