'use client';
import Link from 'next/link';
import {useState} from 'react';
import {Carousel,CarouselContent,CarouselItem,CarouselPrevious,CarouselNext} from '@/components/ui/carousel';
import {Accordion,AccordionItem,AccordionTrigger,AccordionContent} from '@/components/ui/accordion';
import {ArrowRight,ArrowLeft,Expand} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {EditableImage,EditableSection,EditableText,useCms} from './cms';
import {eventPhotos} from '@/lib/event-content';
type ServiceBlock={id:string;eyebrow:string;title:string;copy:string;features:string[];category:'Weddings'|'Events';image:string;reverse?:boolean;cta:{href:string;label:string};anchor?:string};
const services:ServiceBlock[]=[
{id:'ceremony',eyebrow:'WEDDING FLOWERS',title:'Wedding flowers',copy:'From your bridal bouquet to the ceremony, each arrangement is designed around your day. Carefully chosen flowers bring a consistent feeling to every space.',features:['Custom bridal bouquets','Ceremony arch decorations','Aisle arrangements','Altar floral displays'],category:'Weddings',image:eventPhotos.find(p=>p.category==='Weddings')?.image??'/images/original-events/event-7.webp',cta:{href:'#event-inquiry',label:'Discuss your flowers'}},
{id:'celebrations',eyebrow:'EVENT FLOWERS',title:'Event flowers',copy:'Floral arrangements for corporate gatherings and private parties, tailored to the occasion. Centerpieces and venue decorations bring your celebration together.',features:['Corporate event arrangements','Private party decorations','Custom centerpieces','Venue transformation'],category:'Events',image:eventPhotos.find(p=>p.category==='Events')?.image??'/images/original-events/event-3.webp',reverse:true,anchor:'event-flowers',cta:{href:'#event-inquiry',label:'Plan your event flowers'}},
{id:'personal-bouquet',eyebrow:'DESIGN YOUR BOUQUET',title:'Design your bouquet',copy:'Choose the flowers and colors you love, with personal guidance from Rebecca. Your bouquet is designed to reflect your style, from its shape to the smallest finishing detail.',features:['Personalized consultations','Wide selection of flowers','Custom color schemes','Expert design guidance'],category:'Weddings',image:'/images/customization-hero.png',anchor:'design-your-bouquet',cta:{href:'/customize',label:'Design your bouquet'}},
];
function WeddingServiceSection({service,index}:{service:ServiceBlock;index:number}){const cta=<>{service.cta.label} <ArrowRight size={16}/></>;return <EditableSection id={service.anchor} className={'wedding-detail-row'+(service.reverse?' reverse':'')} editKey={'wedding-detail-'+service.id}><figure><EditableImage editKey={'wedding-service-photo-'+service.id} src={service.image} alt={service.title+' from the Bexy Flowers portfolio'} width="800" height="900" loading="lazy"/><EditableText as="figcaption" editKey={'wedding-photo-caption-'+service.id}>{service.category==='Weddings'?'A PERSONAL CELEBRATION':'FLOWERS FOR YOUR GATHERING'}</EditableText></figure><div><span className="wedding-detail-number">0{index+1}</span><EditableText as="p" className="eyebrow wedding-service-eyebrow" editKey={'wedding-service-eyebrow-'+service.id}>{service.eyebrow}</EditableText><EditableText as="h2" editKey={'wedding-service-title-'+service.id}>{service.title}</EditableText><EditableText as="p" editKey={'wedding-service-copy-'+service.id}>{service.copy}</EditableText><Accordion type="single" collapsible className="wedding-service-more"><AccordionItem value="details"><AccordionTrigger>What’s included</AccordionTrigger><AccordionContent><ul>{service.features.map((f,n)=><li key={n}><EditableText as="span" editKey={'wedding-service-feature-'+service.id+'-'+n}>{f}</EditableText></li>)}</ul></AccordionContent></AccordionItem></Accordion>{service.cta.href.startsWith('#')?<a className="outline" href={service.cta.href}>{cta}</a>:<Link className="outline" href={service.cta.href}>{cta}</Link>}</div></EditableSection>}
const inclusions=[
['bridal','Bridal bouquet','A personalized bouquet made with fresh, real flowers of your choice.'],
['bridesmaids','Bridesmaid bouquets','Coordinated bouquets that complement your wedding theme.'],
['houses','Bride & groom’s house decorations','Floral arrangements for both homes, styled as part of your celebration.'],
['church','Church decorations','Altar and entrance arrangements combining fresh and artificial flowers.'],
['welcome','Welcome drink decoration','Floral centerpieces and candles for your welcome tables.'],
['party','Party decoration','Dining-table centerpieces for the celebration.'],
['tables','Table centerpieces','Large arrangements using high-quality white artificial flowers.'],
['cars','Car flower decoration','Real-flower decorations for three cars, including the main bridal car.']
];
export function WeddingDetails(){return <><div className="wedding-detail-sections wedding-service-sections">{services.map((s,i)=><WeddingServiceSection key={s.id} service={s} index={i}/>)}</div><EditableSection className="wedding-package wedding-package-slider" editKey="wedding-standard-package"><div className="wedding-package-photo"><EditableImage editKey="wedding-package-overview-photo" src="/images/original-events/event-3.webp" alt="Bexy Flowers reception tables with white floral arrangements" width="1200" height="650" loading="lazy"/></div><div className="wedding-package-heading"><div><EditableText as="p" className="eyebrow" editKey="wedding-package-eyebrow">OUR STANDARD PACKAGE</EditableText><EditableText as="h2" editKey="wedding-package-title">Complete wedding experience</EditableText><EditableText as="p" editKey="wedding-package-intro">A coordinated floral and décor package, from ceremony to reception. Each element can be customized to your day.</EditableText></div><div className="wedding-package-price"><EditableText as="strong" editKey="wedding-package-price">$3,200</EditableText><EditableText as="span" editKey="wedding-package-price-note">Standard package · Customizable</EditableText><EditableText as="small" editKey="wedding-package-confirm">Confirm your final package and quote with Rebecca.</EditableText></div></div><Carousel className="wedding-inclusions-carousel" opts={{align:"start"}} aria-label="Eight wedding package inclusions"><div className="wedding-slider-controls"><span>8 details, one celebration · Swipe to explore</span><CarouselPrevious/><CarouselNext/></div><CarouselContent className="wedding-package-inclusions">{inclusions.map(([id,title,copy],i)=><CarouselItem key={id}><article><span>0{i+1}</span><div><EditableText as="h3" editKey={'wedding-inclusion-title-'+id}>{title}</EditableText><EditableText as="p" editKey={'wedding-inclusion-copy-'+id}>{copy}</EditableText></div></article></CarouselItem>)}</CarouselContent></Carousel><a className="primary" href="#event-inquiry">Reserve a meeting <ArrowRight size={16}/></a></EditableSection></>}
export function WeddingPortfolio(){const[category,setCategory]=useState('All');const[selected,setSelected]=useState<number|null>(null);const{editing,cms}=useCms();const list=eventPhotos.filter(p=>category==='All'||p.category===category);const photo=selected===null?null:list[selected];return <EditableSection className="wedding-full-gallery" editKey="wedding-full-portfolio"><div className="wedding-gallery-heading"><div><EditableText as="p" className="eyebrow" editKey="wedding-full-gallery-eyebrow">FROM THE BEXY PORTFOLIO</EditableText><EditableText as="h2" editKey="wedding-full-gallery-title">Our wedding & event creations</EditableText></div><div className="wedding-gallery-filters" aria-label="Filter portfolio">{['All','Weddings','Events'].map(c=><button key={c} aria-pressed={category===c} onClick={()=>{setCategory(c);setSelected(null)}}>{c}</button>)}</div></div><div className="wedding-full-gallery-grid">{list.map((p,i)=><figure key={p.id}><div className="wedding-gallery-photo"><EditableImage src={p.image} alt={p.caption} editKey={'wedding-portfolio-photo-'+p.id} width="700" height="850" loading="lazy"/>{!editing&&<button aria-label={'Enlarge '+p.caption} onClick={()=>setSelected(i)}><Expand size={18}/></button>}</div><EditableText as="figcaption" editKey={'wedding-portfolio-caption-'+p.id}>{p.caption}</EditableText></figure>)}</div><Dialog open={photo!==null} onOpenChange={v=>{if(!v)setSelected(null)}}><DialogContent className="wedding-lightbox"><DialogTitle>{photo?(cms.entries['wedding-portfolio-caption-'+photo.id]?.text??photo.caption):'Photo'}</DialogTitle><DialogDescription>{photo?.category} · Bexy Flowers</DialogDescription>{photo&&<img src={cms.entries['wedding-portfolio-photo-'+photo.id]?.src??photo.image} alt={cms.entries['wedding-portfolio-photo-'+photo.id]?.alt??photo.caption}/>}<div><button className="outline" aria-label="Previous photo" onClick={()=>setSelected(v=>((v??0)-1+list.length)%list.length)}><ArrowLeft size={18}/></button><span>{(selected??0)+1} / {list.length}</span><button className="outline" aria-label="Next photo" onClick={()=>setSelected(v=>((v??0)+1)%list.length)}><ArrowRight size={18}/></button></div></DialogContent></Dialog></EditableSection>}
