import {env} from 'cloudflare:workers';
import {z} from 'zod';
import {initialCms,upgradeCms,type CmsData} from '@/lib/demo-data';
import {readData} from '@/lib/server-demo';
import {productUnitPrice} from '@/lib/product-options';
import {designPrice} from '@/lib/atelier';
import {storeState as state} from '@/lib/store-schema';
const draft=z.object({name:z.string().trim().min(2).max(100),phone:z.string().regex(/^\+?[0-9 ()-]{7,22}$/),recipient:z.string().trim().min(2).max(100),city:z.string().trim().min(2).max(100),address:z.string().trim().min(5).max(500),date:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>v>=new Date().toISOString().slice(0,10),'Choose a future delivery date'),message:z.string().max(1000)});
function session(req:Request){const match=req.headers.get('cookie')?.match(/(?:^|;\s*)bexy_session=([a-f0-9-]{36})(?:;|$)/);return match?.[1]??crypto.randomUUID()}
function response(data:unknown,id:string,status=200){return Response.json(data,{status,headers:{'Cache-Control':'no-store','Set-Cookie':`bexy_session=${id}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=2592000`}})}
export async function GET(req:Request){const id=session(req);try{const row=await env.DB.prepare('SELECT data FROM shop_sessions WHERE id = ?').bind(id).first<{data:string}>();return response(row?JSON.parse(row.data):{cart:[],favorites:[],design:null},id)}catch{return response({error:'Your saved items could not be loaded. Please try again.'},id,503)}}
export async function POST(req:Request){const id=session(req);const origin=req.headers.get('origin');if(!origin||origin!==new URL(req.url).origin)return response({error:'Invalid request origin.'},id,403);try{const raw=await req.text();if(raw.length>60000)return response({error:'Request too large.'},id,413);const body=JSON.parse(raw);
if(body.action==='draft'){const details=draft.parse(body.details);const row=await env.DB.prepare('SELECT data FROM shop_sessions WHERE id = ?').bind(id).first<{data:string}>();const saved=state.parse(row?JSON.parse(row.data):{});if(!saved.cart.length)return response({error:'Your bag is empty.'},id,400);const cms=upgradeCms(await readData<CmsData>('cms',initialCms));const lines=saved.cart.map(i=>{const p=cms.products.find(p=>p.id===i.productId);return {productId:i.productId,size:i.size,quantity:i.quantity,unitPrice:i.config?.atelier?designPrice(i.config).total:p?productUnitPrice(p,i.size,cms.entries):null}});const pricing={lines,subtotal:lines.reduce((n,l)=>n+(l.unitPrice??0)*l.quantity,0),delivery:'quoted separately',currency:'USD'};const orderId=crypto.randomUUID();await env.DB.prepare('INSERT INTO order_drafts (id,session_id,data,created_at) VALUES (?,?,?,?)').bind(orderId,id,JSON.stringify({details,cart:saved.cart,pricing,status:'draft',country:'Lebanon'}),Date.now()).run();return response({id:orderId,status:'draft'},id)}
const data=state.parse(body);const cms=upgradeCms(await readData<CmsData>('cms',initialCms));if(data.cart.some(i=>i.productId!=='custom'&&!cms.products.some(p=>p.id===i.productId)))return response({error:'An arrangement in your bag is no longer available. Please remove it.'},id,400);await env.DB.prepare('INSERT INTO shop_sessions (id,data,updated_at) VALUES (?,?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data,updated_at=excluded.updated_at').bind(id,JSON.stringify(data),Date.now()).run();return response(data,id)
}catch(e){if(e instanceof z.ZodError)return response({error:e.issues[0]?.message??'Please check your details.'},id,400);return response({error:'We could not save your changes. Please try again.'},id,503)}}
