import {analyticsEvent} from '@/lib/visitor-analytics';
import {db} from '@/lib/server-commerce';
import {identity,sameOrigin,json,readData} from '@/lib/server-demo';
import {initialCms,upgradeCms,type CmsData} from '@/lib/demo-data';
const visitorCookie=(req:Request)=>req.headers.get('cookie')?.match(/(?:^|;\s*)bexy_visitor=([a-f0-9-]{36})(?:;|$)/)?.[1];
export async function POST(req:Request){if(!sameOrigin(req))return json({error:'Invalid request origin.'},403);try{if((await identity(req))?.role==='admin')return json({ignored:true});const raw=await req.text();if(raw.length>2000)return json({error:'Request too large.'},413);const parsed=analyticsEvent.safeParse(JSON.parse(raw));if(!parsed.success)return json({error:'Invalid event.'},400);const v=parsed.data;const id=visitorCookie(req)??crypto.randomUUID(),now=Date.now();if(v.type==='cart_add'&&v.productId!=='custom'){const cms=upgradeCms(await readData<CmsData>('cms',initialCms));if(!cms.products.some(p=>p.id===v.productId))return json({error:'Unknown product.'},400)}
if(v.type!=='heartbeat'){const recent=await db().prepare('SELECT COUNT(*) n FROM analytics_events WHERE visitor_id=? AND created_at>?').bind(id,now-60000).first<{n:number}>();if((recent?.n??0)>80)return json({error:'Please slow down.'},429);}
const statements=[];
// Thirty minutes of inactivity starts a new visit. Check before updating presence.
statements.push(db().prepare("INSERT INTO analytics_events (id,visitor_id,view_id,type,page,quantity,depth,created_at) SELECT ?,?,?,'visit',?,0,0,? WHERE NOT EXISTS (SELECT 1 FROM analytics_visitors WHERE id=? AND last_seen>?) AND NOT EXISTS (SELECT 1 FROM analytics_events WHERE id=?)").bind(crypto.randomUUID(),id,v.viewId,v.page,now,id,now-1800000,v.id));
if(v.type!=='heartbeat')statements.push(db().prepare('INSERT INTO analytics_events (id,visitor_id,view_id,type,page,product_id,quantity,depth,created_at) VALUES (?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO NOTHING').bind(v.id,id,v.viewId,v.type,v.page,v.productId??null,v.quantity??0,v.depth,now));
statements.push(db().prepare('INSERT INTO analytics_visitors (id,last_seen,page,scrolling) VALUES (?,?,?,?) ON CONFLICT(id) DO UPDATE SET last_seen=excluded.last_seen,page=excluded.page,scrolling=excluded.scrolling').bind(id,now,v.page,v.scrolling?1:0));
await db().batch(statements);return Response.json({ok:true},{headers:{'Cache-Control':'no-store','Set-Cookie':`bexy_visitor=${id}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=7776000`}})
}catch{ return json({error:'Analytics temporarily unavailable.'},503)}}
export async function GET(req:Request){try{if((await identity(req))?.role!=='admin')return json({error:'Admin sign-in required.'},403);const days=Number(new URL(req.url).searchParams.get('days')??30);if(![1,7,30,90].includes(days))return json({error:'Invalid period.'},400);const now=Date.now(),from=now-days*86400000;
const results=await db().batch<Record<string,string|number|null>>([
 db().prepare("SELECT COUNT(DISTINCT visitor_id) visitors,SUM(CASE WHEN type='visit' THEN 1 ELSE 0 END) visits,SUM(CASE WHEN type='page_view' THEN 1 ELSE 0 END) views,SUM(CASE WHEN type='cart_add' THEN 1 ELSE 0 END) cartAdds,SUM(CASE WHEN type='cart_add' THEN quantity ELSE 0 END) cartUnits FROM analytics_events WHERE created_at>=?").bind(from),
 db().prepare('SELECT COUNT(*) active,COALESCE(SUM(scrolling),0) scrolling FROM analytics_visitors WHERE last_seen>?').bind(now-45000),
 db().prepare("SELECT date(created_at/1000,'unixepoch') day,COUNT(DISTINCT visitor_id) visitors,SUM(CASE WHEN type='page_view' THEN 1 ELSE 0 END) views,SUM(CASE WHEN type='cart_add' THEN 1 ELSE 0 END) cartAdds FROM analytics_events WHERE created_at>=? GROUP BY day ORDER BY day").bind(from),
 db().prepare("SELECT page,SUM(views) views,COUNT(DISTINCT visitor_id) visitors,ROUND(AVG(depth)) averageDepth FROM (SELECT page,visitor_id,view_id,SUM(CASE WHEN type='page_view' THEN 1 ELSE 0 END) views,MAX(depth) depth FROM analytics_events WHERE created_at>=? AND type IN ('page_view','scroll') GROUP BY page,visitor_id,view_id) GROUP BY page ORDER BY views DESC").bind(from),
 db().prepare("SELECT product_id productId,COUNT(*) adds,SUM(quantity) units FROM analytics_events WHERE created_at>=? AND type='cart_add' GROUP BY product_id ORDER BY adds DESC").bind(from),
 db().prepare("SELECT id,visitor_id visitor,type,page,product_id productId,quantity,depth,created_at createdAt FROM analytics_events WHERE created_at>=? AND type IN ('page_view','scroll','cart_add') ORDER BY created_at DESC LIMIT 40").bind(from)
]);const cms=upgradeCms(await readData<CmsData>('cms',initialCms));const summary=Object.fromEntries(Object.entries(results[0].results[0]??{}).map(([k,v])=>[k,Number(v??0)]));return json({summary,...results[1].results[0],days:results[2].results,pages:results[3].results,products:results[4].results.map(p=>({...p,name:p.productId==='custom'?'Custom bouquet':cms.products.find(x=>x.id===p.productId)?.name??'Archived arrangement'})),activity:results[5].results.map(r=>({...r,visitor:String(r.visitor).slice(0,8).toUpperCase()})),generatedAt:now})
}catch{return json({error:'Unable to load visitor analytics. Please try again.'},503)}}
