import {env} from 'cloudflare:workers';
import {z} from 'zod';
import {identity,sameOrigin,json} from '@/lib/server-demo';
async function hash(password:string,salt:string){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']);const b=await crypto.subtle.deriveBits({name:'PBKDF2',salt:new TextEncoder().encode(salt),iterations:100000,hash:'SHA-256'},key,256);return Array.from(new Uint8Array(b)).map(x=>x.toString(16).padStart(2,'0')).join('')}
export async function GET(req:Request){try{return json({user:await identity(req)})}catch{return json({error:'Unable to load your demo account.'},503)}}
export async function POST(req:Request){if(!sameOrigin(req))return json({error:'Invalid request origin.'},403);try{const raw=await req.text();if(raw.length>5000)return json({error:'Request too large.'},413);const body=JSON.parse(raw);if(body.action==='logout'){const token=req.headers.get('cookie')?.match(/bexy_demo_auth=([a-f0-9-]{36})/)?.[1];if(token)await env.DB.prepare('DELETE FROM demo_auth WHERE token=?').bind(token).run();return Response.json({user:null},{headers:{'Set-Cookie':'bexy_demo_auth=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0','Cache-Control':'no-store'}})}
let user:{id:string;name:string;email:string;role:string};if(body.action==='admin'){if(body.username!=='admin'||body.password!=='admin123')return json({error:'Incorrect username or password.'},401);user={id:'admin',name:'Rebecca',email:'admin',role:'admin'}}else if(body.action==='signup'){const b=z.object({name:z.string().trim().min(2).max(100),email:z.string().email().max(200),phone:z.string().max(30),password:z.string().min(6).max(128)}).parse(body);const email=b.email.toLowerCase();if(await env.DB.prepare('SELECT id FROM demo_users WHERE email=?').bind(email).first())return json({error:'A demo account already exists for this email.'},409);const id=crypto.randomUUID(),salt=crypto.randomUUID();await env.DB.prepare('INSERT INTO demo_users (id,email,name,phone,hash,salt) VALUES (?,?,?,?,?,?)').bind(id,email,b.name,b.phone,await hash(b.password,salt),salt).run();user={id,email,name:b.name,role:'customer'}}else if(body.action==='login'){const b=z.object({email:z.string().email().max(200),password:z.string().min(1).max(128)}).parse(body);const row=await env.DB.prepare('SELECT * FROM demo_users WHERE email=?').bind(b.email.toLowerCase()).first<{id:string;name:string;email:string;hash:string;salt:string}>();if(!row||await hash(b.password,row.salt)!==row.hash)return json({error:'Incorrect email or password. Create a demo account first.'},401);user={id:row.id,name:row.name,email:row.email,role:'customer'}}else return json({error:'Invalid action.'},400);
const token=crypto.randomUUID();await env.DB.prepare('INSERT INTO demo_auth (token,user_id,role,expires) VALUES (?,?,?,?)').bind(token,user.id,user.role,Date.now()+86400000).run();return Response.json({user},{headers:{'Cache-Control':'no-store','Set-Cookie':`bexy_demo_auth=${token}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=86400`}})
}catch(e){return json({error:e instanceof z.ZodError?e.issues[0].message:'Unable to complete this action. Please try again.'},400)}}
