import {bookConsultation} from '@/lib/server-booking';
import {z} from 'zod';
import {identity,sameOrigin,json,readData} from '@/lib/server-demo';
import {db,listRequests,createRequest,shopSession} from '@/lib/server-commerce';
import {deliverySchema,enquirySchema,snapshot,applyUpdate,updateSchema,type RequestData} from '@/lib/commerce';
import {initialCms,upgradeCms,type CmsData} from '@/lib/demo-data';
import {storeState} from '@/lib/store-schema';
export async function GET(req:Request){try{const admin=new URL(req.url).searchParams.get('admin')==='1';if(admin&&(await identity(req))?.role!=='admin')return json({error:'Admin sign-in required.'},403);return json({requests:await listRequests(req,admin)})}catch{return json({error:'Unable to load requests. Please try again.'},503)}}
export async function POST(req:Request){if(!sameOrigin(req))return json({error:'Invalid request origin.'},403);try{const raw=await req.text();if(raw.length>12000)return json({error:'Request too large.'},413);const body=JSON.parse(raw);if(body.action==='update'){if((await identity(req))?.role!=='admin')return json({error:'Admin sign-in required.'},403);const v=updateSchema.parse(body);const row=await db().prepare('SELECT kind,data,version FROM commerce_requests WHERE id=?').bind(v.id).first<{kind:string;data:string;version:number}>();if(!row)return json({error:'Request not found.'},404);const data=applyUpdate(JSON.parse(row.data),v,row.kind);const result=await db().prepare('UPDATE commerce_requests SET data=?,version=version+1 WHERE id=? AND version=?').bind(JSON.stringify(data),v.id,v.version).run();if(!result.meta.changes)return json({error:'This request changed in another window. Refresh before saving.'},409);return json({ok:true})}
const id=z.string().uuid().parse(body.id);const kind=z.enum(['order','event']).parse(body.kind);const details=kind==='order'?deliverySchema.parse(body.details):enquirySchema.parse(body.details);let lines:RequestData['lines']=[];if(kind==='order'){const row=await db().prepare('SELECT data FROM shop_sessions WHERE id=?').bind(shopSession(req)??'').first<{data:string}>();const state=storeState.parse(row?JSON.parse(row.data):{cart:[],favorites:[],design:null});lines=snapshot(state.cart,upgradeCms(await readData<CmsData>('cms',initialCms)))}const data:RequestData={details,lines,subtotal:lines.reduce((s,l)=>s+l.quantity*l.unitPrice,0),shipping:0,paid:0,refund:0,payment:'Not recorded',status:kind==='order'?'Pending':'New',notes:'',history:[{date:new Date().toISOString(),note:'Request received'}]};if(kind==='event'&&data.details.consultationSlotId){await bookConsultation(req,id,String(data.details.consultationSlotId),data)}else{await createRequest(req,id,kind,data)}return json({id,status:data.status},201)
}catch(e){if(e instanceof z.ZodError)return json({error:e.issues[0]?.message??'Please check your details.'},400);if(e instanceof SyntaxError)return json({error:'Invalid request.'},400);console.error('Request operation failed',e);return json({error:e instanceof Error&&!/D1|SQL|database/i.test(e.message)?e.message:'Unable to save. Please try again.'},400)}}
