import {studioFlowers} from './studio-flowers';
import type {BouquetConfig} from './catalog';
export type FlowerSelection={id:string;quantity:number;position:'center'|'edges'|'scattered'|'accent'};
export type AtelierConfig={presentation:'box'|'wrap';boxShape:'round'|'square'|'heart'|'rectangle';bouquetShape:'classic'|'heart'|'letter'|'number'|'cascade'|'sunburst';letter:string;number:string;size:'small'|'medium'|'large';color:string;mode:'specific'|'mix';family:string;flowers:FlowerSelection[];arrangement:'dome'|'flat'|'cascading';density:'tight'|'medium'|'airy';bloom:'full'|'semi'|'mixed';ribbon:boolean;accessories:string[]};
export const sizes=[{id:'small',name:'Small',capacity:10,multiplier:1},{id:'medium',name:'Medium',capacity:22,multiplier:1.5},{id:'large',name:'Large',capacity:37,multiplier:2}] as const;
export const packageColors=[{name:'Black',hex:'#000000'},{name:'White',hex:'#ffffff'},{name:'Gold',hex:'#c79e48'},{name:'Pink',hex:'#ffc0cb'},{name:'Blue',hex:'#87ceeb'},{name:'Red',hex:'#dc143c'},{name:'Purple',hex:'#9b59b6'},{name:'Forest Green',hex:'#2ecc71'},{name:'Beige',hex:'#f5e6d3'},{name:'Burgundy',hex:'#800020'}];
export const studioAccessories=[{id:'crown',name:'Crown',price:500},{id:'graduation-hat',name:'Graduation Hat',price:400},{id:'bear',name:'Teddy Bear',price:600},{id:'chocolate',name:'Chocolates',price:300},{id:'balloons',name:'Balloons',price:700},{id:'number-candles',name:'Number Candles',price:400},{id:'photo-frame',name:'Photo Frame',price:800},{id:'candles',name:'Candles',price:500},{id:'stickers',name:'Custom Stickers',price:300},{id:'banner',name:'Mini Banner',price:400},{id:'stars',name:'Star Confetti',price:200},{id:'ribbon-bow',name:'Luxury Ribbon',price:300},{id:'accessory-spiderman',name:'Spider-Man Topper',price:800},{id:'accessory-minion',name:'Minion Topper',price:800}];
export const flowerColors:Record<string,string>={red:'#aa253a',white:'#fff7ee',pink:'#ed8bab',yellow:'#f4ce56',blue:'#315dbb',peach:'#efa680',fushia:'#bf307b',orange:'#ed8a38',purple:'#9662b3','dark blue':'#193872',terracotta:'#bc6b4e'};
export const defaultAtelier:AtelierConfig={presentation:'wrap',boxShape:'round',bouquetShape:'classic',letter:'R',number:'21',size:'medium',color:'#000000',mode:'mix',family:'all',flowers:[],arrangement:'dome',density:'tight',bloom:'full',ribbon:false,accessories:[]};
export const stemCount=(a:AtelierConfig)=>a.flowers.reduce((s,f)=>s+f.quantity,0);
export function bouquetByTheme(base:BouquetConfig,theme:string|null):BouquetConfig{
 if(theme!=='valentine'&&theme!=='birthday')return withAtelier(base,normalizeAtelier(base));
 const birthday=theme==='birthday';
 return withAtelier(base,{...defaultAtelier,presentation:'box',boxShape:'round',size:'medium',family:'roses',ribbon:true,flowers:birthday?[{id:'rose-blue',quantity:14,position:'scattered'},{id:'rose-white',quantity:8,position:'scattered'}]:[{id:'rose-red',quantity:22,position:'scattered'}],accessories:birthday?['crown','stars','ribbon-bow','chocolate']:['chocolate','ribbon-bow']});
}
export const capacity=(a:AtelierConfig)=>sizes.find(s=>s.id===a.size)!.capacity;
export function normalizeAtelier(c:BouquetConfig):AtelierConfig{if(c.atelier)return c.atelier;const nearest=(family:string,color:string)=>studioFlowers.filter(f=>f.family===family).find(f=>flowerColors[f.colorName].toLowerCase()===color.toLowerCase())??studioFlowers.find(f=>f.family===family)!;const flowers:FlowerSelection[]=[];if(c.roses)flowers.push({id:nearest('roses',c.roseColor).id,quantity:c.roses,position:'scattered'});if(c.tulips)flowers.push({id:nearest('tulips',c.tulipColor).id,quantity:c.tulips,position:'scattered'});if(c.peonies)flowers.push({id:'peony-white',quantity:c.peonies,position:'scattered'});let left=37;const trimmed=flowers.map(f=>{const quantity=Math.min(left,f.quantity);left-=quantity;return {...f,quantity}}).filter(f=>f.quantity>0);const count=trimmed.reduce((n,f)=>n+f.quantity,0);return {...defaultAtelier,flowers:trimmed,color:c.wrap,size:count>22?'large':count>10?'medium':'small'}}
export function withAtelier(c:BouquetConfig,a:AtelierConfig):BouquetConfig{const n=(family:string)=>a.flowers.filter(s=>studioFlowers.find(f=>f.id===s.id)?.family===family).reduce((s,f)=>s+f.quantity,0);return {...c,atelier:a,roses:n('roses'),tulips:n('tulips'),peonies:n('peonies'),wrap:a.color}}
export function designPrice(c:BouquetConfig){const a=normalizeAtelier(c);const packaging=Math.round((a.presentation==='box'?2000:1500)*sizes.find(s=>s.id===a.size)!.multiplier);const flowers=a.flowers.reduce((sum,s)=>sum+(studioFlowers.find(f=>f.id===s.id)?.price??0)*s.quantity,0);const extras=(c.glitter?200:0)+a.accessories.reduce((sum,id)=>sum+(studioAccessories.find(x=>x.id===id)?.price??0),0);return {packaging,flowers,extras,total:packaging+flowers+extras}}
export function describeDesign(c:BouquetConfig){const a=normalizeAtelier(c);return [a.size+' '+a.presentation+' · '+(a.presentation==='box'?a.boxShape:a.bouquetShape),a.flowers.map(s=>`${s.quantity} ${studioFlowers.find(f=>f.id===s.id)?.name??s.id} (${s.position})`).join(', '),`${a.arrangement}, ${a.density}, ${a.bloom} blooms`,a.bouquetShape==='letter'?'Letter: '+a.letter:a.bouquetShape==='number'?'Number: '+a.number:'',c.glitter?'Glitter':'',a.ribbon?'Satin ribbon':'',a.accessories.map(id=>studioAccessories.find(x=>x.id===id)?.name).filter(Boolean).join(', '),c.note].filter(Boolean).join('\n')}
