import {z} from 'zod';
import type {CartItem} from './catalog';
import type {CmsData,AdminData} from './demo-data';
import {productUnitPrice} from './product-options';
import {designPrice,describeDesign} from './atelier';
export const orderStatuses=['Pending','Confirmed','Preparing','Out for delivery','Delivered','Cancelled'] as const;
export const eventStatuses=['New','Contacted','Proposal sent','Booked','Completed','Cancelled'] as const;
const date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>!Number.isNaN(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v,'Choose a valid date');
const future=date.refine(v=>v>=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Beirut',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()),'Choose today or a future date');
export const deliverySchema=z.object({name:z.string().trim().min(2).max(100),email:z.string().trim().email().max(200),phone:z.string().regex(/^\+?[0-9 ()-]{7,22}$/),recipient:z.string().trim().min(2).max(100),city:z.string().trim().min(2).max(100),address:z.string().trim().min(5).max(500),date:future,message:z.string().max(1000),occasion:z.string().max(100).default('Just because'),consent:z.boolean().default(false)});
export const enquirySchema=z.object({name:z.string().trim().min(2).max(100),email:z.string().trim().email().max(200),phone:z.string().regex(/^\+?[0-9 ()-]{7,22}$/),type:z.enum(['Wedding','Engagement','Birthday','Private event','Corporate event']),date:future,consultationSlotId:z.union([z.string().uuid(),z.literal('')]).default(''),venue:z.string().trim().min(2).max(300),message:z.string().max(3000)});
export type OrderLine={productId:string;name:string;quantity:number;unitPrice:number;cost:number;stems:number;size:string;note:string;design?:string;config?:CartItem['config']};
export type RequestData={details:Record<string,string|boolean>;lines:OrderLine[];subtotal:number;shipping:number;paid:number;refund:number;payment:string;status:string;notes:string;history:{date:string;note:string}[]};
export type StoreRequest={id:string;kind:'order'|'event';createdAt:number;version:number;data:RequestData};
export function snapshot(cart:CartItem[],cms:CmsData):OrderLine[]{if(!cart.length)throw Error('Your bag is empty.');const quantities=new Map<string,number>();return cart.map(i=>{if(i.productId==='custom'){if(!i.config?.atelier)throw Error('Please open the bouquet studio and update your custom design.');return {productId:'custom',name:'Custom bouquet',quantity:i.quantity,unitPrice:designPrice(i.config).total,cost:0,stems:i.config.atelier.flowers.reduce((n,f)=>n+f.quantity,0),size:i.size,note:i.note,design:describeDesign(i.config),config:i.config}}const p=cms.products.find(p=>p.id===i.productId);if(!p||p.active===false)throw Error('An arrangement is no longer available. Please update your bag.');const count=(quantities.get(p.id)??0)+i.quantity;quantities.set(p.id,count);if(count>(p.stock??0))throw Error(`${p.name} has insufficient availability. Please reduce the quantity.`);if(i.config||!(p.kind==='accessory'?['One size']:['Petite','Signature','Grand']).includes(i.size))throw Error('Please choose a valid arrangement size.');return {productId:p.id,name:p.name,quantity:i.quantity,unitPrice:productUnitPrice(p,i.size,cms.entries),cost:p.cost??0,stems:0,size:i.size,note:i.note}})}
export const updateSchema=z.object({id:z.string().uuid(),version:z.number().int().min(0),status:z.string(),shipping:z.number().int().min(0).max(100000000),paid:z.number().int().min(0).max(100000000),refund:z.number().int().min(0).max(100000000),payment:z.enum(['Not recorded','Cash on delivery','Bank transfer','Other offline payment']),notes:z.string().max(3000)});
export function applyUpdate(old:RequestData,input:z.infer<typeof updateSchema>,kind:string){if(!(kind==='order'?orderStatuses:eventStatuses).includes(input.status as never))throw Error('Invalid status.');if(kind==='event'&&(input.paid||input.refund||input.shipping))throw Error('Event payments are agreed separately.');if(input.refund>input.paid||input.paid>old.subtotal+input.shipping)throw Error('Check payment and refund amounts against the order total.');if(input.paid>0&&input.payment==='Not recorded')throw Error('Choose the payment method.');if(input.status==='Cancelled'&&input.paid!==input.refund)throw Error('Record the actual refund before cancelling a paid order.');return {...old,status:input.status,shipping:input.shipping,paid:input.paid,refund:input.refund,payment:input.payment,notes:input.notes,history:[...old.history,{date:new Date().toISOString(),note:`${input.status} · recorded paid ${input.paid/100} USD · refunded ${input.refund/100} USD · delivery ${input.shipping/100} USD`}].slice(-100)}}
export function adminRecords(records:StoreRequest[],expenses:AdminData['expenses']):AdminData{const customers=new Map<string,AdminData['customers'][number]>();const orders=records.filter(r=>r.kind==='order').map(r=>{const d=r.data,c=d.details,id=String(c.email).toLowerCase();customers.set(id,{id,name:String(c.name),email:String(c.email),phone:String(c.phone),city:String(c.city),consent:c.consent===true});return {id:r.id,date:new Date(r.createdAt).toISOString(),customerId:id,items:d.lines,discount:0,shipping:d.shipping,paid:d.paid,refund:d.refund,status:d.status,payment:d.payment,occasion:String(c.occasion??'Just because')}});return {customers:[...customers.values()],orders,expenses,campaigns:[]}}
