import {products,accessoryProducts,occasionProducts,type Product} from './catalog';
import {rebeccaCatalogProducts} from './rebecca-catalog';
export type CmsEntry={text?:string;src?:string;alt?:string;hidden?:boolean};
export type CmsData={entries:Record<string,CmsEntry>;products:Product[]};
export const initialCms:CmsData={entries:{},products:[...rebeccaCatalogProducts,...products.map((p,i)=>({...p,kind:'flower' as const,years:[2026,2025],occasions:[['Valentine’s Day','Just because'],['Valentine’s Day'],['Mother’s Day','Just because'],['Birthdays'],['Weddings'],['Graduation','Father’s Day']][i],price:[8500,6500,5500,7500,35000,6000][i],cost:[3400,2600,2100,3000,14500,2400][i],discount:i===1?10:0,stock:[28,35,22,18,8,25][i],active:true})),...accessoryProducts,...occasionProducts]};
export const money=(cents:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(cents/100);
export const salePrice=(p:Product)=>Math.round((p.price??0)*(1-(p.discount??0)/100));
export type DemoOrder={id:string;date:string;customerId:string;items:{productId:string;name:string;quantity:number;unitPrice:number;cost:number;stems:number}[];discount:number;shipping:number;paid:number;refund:number;status:string;payment:string;occasion:string};
export const demoCustomers=Array.from({length:18},(_,i)=>({id:'customer-'+(i+1),name:['Nour Haddad','Maya Khalil','Jad Nasser','Lina Khoury','Rami Daher','Sara Mansour','Karim Salem','Lea Farah','Omar Saad','Dana Azar','Tala Najjar','Ziad Karam','Rita Elias','Ali Hamdan','Yara Fares','Roy Tannous','Hala Assaf','Sami Aoun'][i],email:'customer'+(i+1)+'@example.com',phone:'+961 XX XXX '+String(i+1).padStart(3,'0'),city:['Beirut','Sidon','Jounieh','Byblos','Tripoli','Zahle'][i%6],consent:i%5!==0}));
export const demoOrders:DemoOrder[]=Array.from({length:420},(_,i)=>{const p=initialCms.products[i%6];const d=new Date(Date.UTC(2025,8,8));d.setUTCDate(d.getUTCDate()+Math.floor(i*365/420));d.setUTCHours((i*7)%24,15);const quantity=1+i%3;const gross=p.price!*quantity;const discount=i%7===0?Math.round(gross*.1):0;const shipping=i%6===0?0:500;const status=i%29===0?'Cancelled':i%23===0?'Refunded':i%17===0?'Pending':i>413?'Preparing':'Delivered';const refund=status==='Refunded'?gross-discount+shipping:0;return{id:'BX-'+String(1001+i),date:d.toISOString(),customerId:demoCustomers[i%18].id,items:[{productId:p.id,name:p.name,quantity,unitPrice:p.price!,cost:p.cost!,stems:[24,18,15,21,70,16][i%6]}],discount,shipping,paid:status==='Pending'||status==='Cancelled'?0:gross-discount+shipping,refund,status,payment:['Cash on delivery','Card','Bank transfer'][i%3],occasion:d.getUTCMonth()===1?'Valentine’s Day':d.getUTCMonth()===2?'Mother’s Day':p.category==='Weddings'?'Wedding':i%4===0?'Birthday':'Just because'}});
export const demoExpenses=Array.from({length:13},(_,i)=>({id:'expense-'+i,date:new Date(Date.UTC(2025,8+i,1)).toISOString().slice(0,10),name:'Studio, delivery & operating costs',amount:125000+i*2500}));
export type AdminData={customers:typeof demoCustomers;orders:DemoOrder[];expenses:typeof demoExpenses;campaigns:{id:string;date:string;channel:string;recipientIds:string[];message:string;status:string}[]};
export const initialAdmin:AdminData={customers:demoCustomers,orders:demoOrders,expenses:demoExpenses,campaigns:[]};
export function totals(orders:DemoOrder[]){const active=orders.filter(o=>o.status!=='Cancelled');const grossOf=(o:DemoOrder)=>o.items.reduce((s,i)=>s+i.unitPrice*i.quantity,0);const netOf=(o:DemoOrder)=>Math.max(0,grossOf(o)-o.discount);const ratio=(o:DemoOrder)=>{const due=netOf(o)+o.shipping;return due>0?Math.min(1,Math.max(0,o.paid-o.refund)/due):0};const recognized=active.filter(o=>ratio(o)>0);const revenue=recognized.reduce((s,o)=>s+Math.round(netOf(o)*ratio(o)),0);const cost=recognized.reduce((s,o)=>s+Math.round(o.items.reduce((a,i)=>a+i.cost*i.quantity,0)*ratio(o)),0);return{gross:active.reduce((s,o)=>s+grossOf(o),0),discounts:active.reduce((s,o)=>s+o.discount,0),collected:orders.reduce((s,o)=>s+o.paid-o.refund,0),revenue,cost,refunds:orders.reduce((s,o)=>s+o.refund,0),shipping:recognized.reduce((s,o)=>s+Math.round(o.shipping*ratio(o)),0),outstanding:active.filter(o=>o.status!=='Refunded').reduce((s,o)=>s+Math.max(0,netOf(o)+o.shipping-o.paid),0),orders:recognized.length,units:recognized.reduce((s,o)=>s+o.items.reduce((a,i)=>a+i.quantity,0),0),stems:recognized.reduce((s,o)=>s+o.items.reduce((a,i)=>a+i.quantity*i.stems,0),0)}};


// Upgrade the previous mock catalog without replacing any owner edits or hidden products.
export function upgradeCms(data:CmsData):CmsData{return {...data,products:[...data.products.map(p=>{const seed=initialCms.products.find(x=>x.id===p.id);return {...p,kind:p.kind??seed?.kind??'flower',occasions:p.occasions??seed?.occasions??[],years:p.years??seed?.years??[2026]}}),...[...rebeccaCatalogProducts,...accessoryProducts,...occasionProducts].filter(p=>!data.products.some(x=>x.id===p.id))]}}
