import {db,shopSession} from './server-commerce';
import {identity} from './server-demo';
import {beirutDate,beirutTime} from './availability';
import type {RequestData} from './commerce';
export async function bookConsultation(req:Request,id:string,slotId:string,data:RequestData){const session=shopSession(req);if(!session)throw Error('Please reload the page before booking.');const old=await db().prepare('SELECT session_id,data FROM commerce_requests WHERE id=?').bind(id).first<{session_id:string;data:string}>();if(old){if(old.session_id!==session||JSON.parse(old.data).details.consultationSlotId!==slotId)throw Error('Please reload and try again.');return}
const slot=await db().prepare("SELECT starts_at,ends_at FROM consultation_slots WHERE id=? AND status='available' AND starts_at>?").bind(slotId,Date.now()).first<{starts_at:number;ends_at:number}>();if(!slot)throw Error('This consultation time is no longer available. Please choose another.');const count=await db().prepare('SELECT COUNT(*) n FROM commerce_requests WHERE session_id=? AND created_at>?').bind(session,Date.now()-3600000).first<{n:number}>();if((count?.n??0)>=10)throw Error('Too many requests. Please try again later.');const user=await identity(req);data.details={...data.details,consultationSlotId:slotId,consultationDate:beirutDate(slot.starts_at),consultationTime:beirutTime(slot.starts_at)+'–'+beirutTime(slot.ends_at)+' (Beirut time)',consultationStatus:'Booked'};
// Both statements run in one D1 transaction. Only one request can claim the slot.
const result=await db().batch([db().prepare("INSERT INTO commerce_requests(id,session_id,user_id,kind,data,version,created_at) SELECT ?,?,?,'event',?,0,? WHERE EXISTS(SELECT 1 FROM consultation_slots WHERE id=? AND status='available' AND starts_at>? AND starts_at=? AND ends_at=?) ON CONFLICT(id) DO NOTHING").bind(id,session,user?.role==='customer'?user.id:null,JSON.stringify(data),Date.now(),slotId,Date.now(),slot.starts_at,slot.ends_at),db().prepare("UPDATE consultation_slots SET status='booked',request_id=?,version=version+1 WHERE id=? AND status='available' AND EXISTS(SELECT 1 FROM commerce_requests WHERE id=? AND session_id=? AND json_extract(data,'$.details.consultationSlotId')=?)").bind(id,slotId,id,session,slotId)]);if(!result[0].meta.changes&&!result[1].meta.changes){const existing=await db().prepare('SELECT request_id FROM consultation_slots WHERE id=?').bind(slotId).first<{request_id:string}>();if(existing?.request_id!==id)throw Error('This consultation time was just booked. Please choose another.')}
}
