import {env} from 'cloudflare:workers';
import {identity} from './server-demo';
import type {RequestData,StoreRequest} from './commerce';
export const db=()=>env.DB;
export const shopSession=(req:Request)=>req.headers.get('cookie')?.match(/(?:^|;\s*)bexy_session=([a-f0-9-]{36})(?:;|$)/)?.[1]??null;
type Row={id:string;kind:'order'|'event';data:string;version:number;created_at:number};
export const decode=(r:Row):StoreRequest=>({id:r.id,kind:r.kind,data:JSON.parse(r.data),version:r.version,createdAt:r.created_at});
export async function listRequests(req:Request,admin=false){const user=await identity(req);if(admin){if(user?.role!=='admin')throw Error('Admin sign-in required.');const rows=await db().prepare('SELECT id,kind,data,version,created_at FROM commerce_requests ORDER BY created_at DESC').all<Row>();return rows.results.map(decode)}const rows=await db().prepare('SELECT id,kind,data,version,created_at FROM commerce_requests WHERE session_id=? OR user_id=? ORDER BY created_at DESC').bind(shopSession(req)??'',user?.id??'').all<Row>();return rows.results.map(decode).map(r=>({...r,data:{...r.data,notes:'',history:[],lines:r.data.lines.map(l=>({...l,cost:0}))}}))}
export async function createRequest(req:Request,id:string,kind:'order'|'event',data:RequestData){const session=shopSession(req);if(!session)throw Error('Please reload the page before submitting.');const user=await identity(req);const old=await db().prepare('SELECT id,session_id FROM commerce_requests WHERE id=?').bind(id).first<{id:string;session_id:string}>();if(old){if(old.session_id!==session)throw Error('Please reload and try again.');return id}const recent=await db().prepare('SELECT COUNT(*) AS n FROM commerce_requests WHERE session_id=? AND created_at>?').bind(session,Date.now()-3600000).first<{n:number}>();if((recent?.n??0)>=10)throw Error('Too many requests. Please try again later.');await db().prepare('INSERT INTO commerce_requests (id,session_id,user_id,kind,data,version,created_at) VALUES (?,?,?,?,?,0,?) ON CONFLICT(id) DO NOTHING').bind(id,session,user?.role==='customer'?user.id:null,kind,JSON.stringify(data),Date.now()).run();return id}
