import {db,listRequests} from '@/lib/server-commerce';
import {adminRecords} from '@/lib/commerce';
import {z} from 'zod';
import {initialAdmin,type AdminData} from '@/lib/demo-data';
import {identity,sameOrigin,readData,writeData,json} from '@/lib/server-demo';
export async function GET(req:Request){try{if((await identity(req))?.role!=='admin')return json({error:'Admin sign-in required.'},403);if(new URL(req.url).searchParams.get('demo')==='1')return json(await readData('admin',initialAdmin));const expenses=await db().prepare('SELECT id,date,name,amount FROM commerce_expenses ORDER BY date').all<AdminData['expenses'][number]>();return json(adminRecords(await listRequests(req,true),expenses.results))}catch{return json({error:'Unable to load the dashboard.'},503)}}
export async function POST(req:Request){try{if(!sameOrigin(req)||(await identity(req))?.role!=='admin')return json({error:'Admin sign-in required.'},403);const raw=await req.text();if(raw.length>10000)return json({error:'Request too large.'},413);const b=JSON.parse(raw) as Record<string,unknown>;if(new URL(req.url).searchParams.get('demo')!=='1'){if(b.action==='expense'){const v=z.object({name:z.string().trim().min(1).max(100),date:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),amount:z.number().int().min(1).max(100000000)}).parse(b);await db().prepare('INSERT INTO commerce_expenses (id,date,name,amount) VALUES (?,?,?,?)').bind(crypto.randomUUID(),v.date,v.name,v.amount).run();return GET(req)}return json({error:b.action==='campaign'?'Email and WhatsApp delivery are not connected. No messages were sent.':'Use Requests & enquiries to manage this order.'},400)}const data=await readData<AdminData>('admin',initialAdmin);if(b.action==='status'){const v=z.object({id:z.string(),status:z.enum(['Pending','Paid','Preparing','Out for delivery','Delivered','Cancelled','Refunded'])}).parse(b);const order=data.orders.find(o=>o.id===v.id);if(!order)return json({error:'Order not found'},404);order.status=v.status;const total=order.items.reduce((s,i)=>s+i.quantity*i.unitPrice,0)-order.discount+order.shipping;if(v.status==='Paid')order.paid=total;if(v.status==='Refunded')order.refund=order.paid;if(v.status!=='Refunded')order.refund=0;if(v.status==='Cancelled'){order.refund=order.paid}}
else if(b.action==='campaign'){const v=z.object({channel:z.enum(['Email','WhatsApp']),recipientIds:z.array(z.string().max(100)).min(1).max(18),message:z.string().min(1).max(2000)}).parse(b);if(v.recipientIds.some(id=>!data.customers.some(c=>c.id===id&&c.consent)))return json({error:'Choose valid opted-in customers.'},400);data.campaigns.unshift({id:crypto.randomUUID(),date:new Date().toISOString(),...v,status:'Simulated — not sent'})}
else if(b.action==='expense'){const v=z.object({name:z.string().min(1).max(100),date:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),amount:z.number().int().min(1).max(100000000)}).parse(b);data.expenses.push({id:crypto.randomUUID(),...v})}else return json({error:'Invalid action'},400);await writeData('admin',data);return json(data)}catch(e){return json({error:e instanceof z.ZodError?e.issues[0].message:'Unable to save changes.'},400)}}
